[webservers]

web-1 ansible_host=51.250.8.38 fqdn=fhmv2l53ouhdho0dred5.auto.internal

web-2 ansible_host=89.169.156.164 fqdn=fhmji4ndt52s2f7v6dgn.auto.internal


[databases]

main ansible_host=51.250.87.140 fqdn=fhmelkt1e40ao2vek2oq.auto.internal

replica ansible_host=89.169.153.121 fqdn=fhm46pivh428s08mpsv2.auto.internal


[storage]

storage ansible_host=89.169.129.63 fqdn=fhm6bu3n3ffl4ioh10sb.auto.internal
