[webservers]

web-1 ansible_host=89.169.144.59 fqdn=fhms6u28161hh479n1vs.auto.internal

web-2 ansible_host=89.169.139.94 fqdn=fhmrlsjcjf1k3nuqskpe.auto.internal


[databases]

main ansible_host=89.169.149.130 fqdn=fhm1321rclf7b9todinh.auto.internal

replica ansible_host=89.169.137.70 fqdn=fhme4vg6r4a9jr6j93j6.auto.internal


[storage]

storage ansible_host=51.250.88.91 fqdn=fhmi4mjr1tdo7p29u2o9.auto.internal
